name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:

  runs-on: ubuntu-latest
  strategy:
    matrix:
      python-version: ['3.10','3.11']
  
  stpes:
    - uses: actions/chekkout@v4
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: try this way
      run: echo "python3 -V"

    - name: Display Python version
      run: python -c "Import sys; print(sys.version)"
    
    