name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10','3.11']
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Show Python version
        run: python3 -V

      - name: Insatll dependcies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # - name: Dockerize the app
      #   run: | 
      #     docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      #     docker images

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Connect to EC2 and run commands
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            whoami
            rm -f /home/${{ secrets.EC2_USER }}/file || echo "file not found"
            /home/${{ secrets.EC2_USER }}/bin/check.sh
          EOF


      - name: Copy repo to EC2
        run: |
          scp -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/my-app
          touch file 

